services:
  - type: web
    name: newstrace-web
    env: python
    branch: main
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m app"

    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SEARCH_ENGINE_ID
        sync: false
      - key: DEBUG
        sync: false
      - key: FLASK_ENV
        value: production

    healthCheckPath: "/"